### ISSUE TITLE
Make 3D Models for Wink Hub devices we want to control

### ISSUE THREAD

**Issue by johanos** [VentanaIoT/Ventana#12]
We just need to choose what functionally Wink Provides for the IoT devices we want to support and then build 3D models to work with these commands (like if we have a light bulb what can we do with it etc...)

Right now looking at lights

**Comment by allydurks** [comment]
first make static 3D models that control a set amount of devices

later, we will come up with a configuration file (primitives) ~ HTML for holograms ~

**Comment by ejfitz** [comment]
Added Light Controller to Assets folder
