### ISSUE TITLE
UX: Feedback sounds

### ISSUE THREAD

**Issue by santybm** [VentanaIoT/Ventana#22]
On user tap and actions, give a feedback sound to the user.

**Comment by johanos** [comment]
We got SOUNDS (and a big open source sound library). We got HIGHLIGHTING that can be abstracted to any button. We got er dunnn

its all in the branch feature-UX/UI_Feedback_sounds 

![bitmoji](https://render.bitstrips.com/v2/cpanel/8149231-126662132_4-s4-v1.png?transparent=1&palette=1&width=246)
