### ISSUE TITLE
UX: Add Visual Indicators to New 3d Models

### ISSUE THREAD

**Issue by santybm** [VentanaIoT/Ventana#23]
- Give user feedback (i.e. depress) on actions

**Comment by santybm** [comment]
Currently code is on the old music player. Add to the new 3D objects.

**Comment by allydurks** [comment]
need to have visual feedback for the mode that is the "moving" mode -- maybe rethink how we move an object?

**Comment by johanos** [comment]
Done on Light and Power Controllers 

pls gtfo
![bitmoji](https://render.bitstrips.com/v2/cpanel/10216447-126662132_8-s4-v1.png?transparent=1&palette=1&width=246)
