### ISSUE TITLE
Third Wink Device: Power Cord

### ISSUE THREAD

**Issue by santybm** [VentanaIoT/Ventana#30]
- Support for streaming video
- Support for Video doorbell or other security device
- Ring video doorbell

**Comment by allydurks** [comment]
Georgew ould like us to do a power strip wink device

**Comment by allydurks** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10117671-208277085_3-s4-v1.png?transparent=1&palette=1&width=246)

because of the modular structure used, this will be a tiny step from light_bulb support
