### ISSUE TITLE
Review HoloToolKit world coordinates and Vuforia compatibilities

### ISSUE THREAD

**Issue by santybm** [VentanaIoT/Ventana#35]

**Comment by tgauth** [comment]
Spawnbehaviourscript creates new controller and tap to place from HoloToolkit allows it to be moved by user. Still needs polish, but WorldCoordinates branch works on HoloLens. ![bitmoji](https://render.bitstrips.com/v2/cpanel/9998079-133928148_5-s4-v1.png?transparent=1&palette=1&width=246)
