### ISSUE TITLE
Finalize image target

### ISSUE THREAD

**Issue by santybm** [VentanaIoT/Ventana#36]

**Comment by johanos** [comment]
can we get a standard size for this thing too? varying sizes messes up prefab scaling. 
![bitmoji](https://render.bitstrips.com/v2/cpanel/8149231-126662132_4-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by ejfitz** [comment]
Absolutely, but we can't/shouldn't do it this sprint. 
We need to have the world anchors piece working so that we can get an idea of what size is comfortable for setting up the location of device before it is passed off to become a world anchor.

**Comment by johanos** [comment]
yeah most def. I just wanted to bring it up that it messes up assigning prefabs (unless we have case by case scaling but that's gross) so that we can think about this for the future.
