### ISSUE TITLE
Rethink how to move objects

### ISSUE THREAD

**Issue by santybm** [VentanaIoT/Ventana#57]
Research how applications move 3d objects and implement a new methodology to the Unity interaction

**Comment by santybm** [comment]
Related to #23

**Comment by tgauth** [comment]
Thought about it. More, done, delete, and resize implemented ![bitmoji](https://render.bitstrips.com/v2/cpanel/7258102-133928148_9-s4-v1.png?transparent=1&palette=1&width=246)
