### ISSUE TITLE
HoloHub Crashing when sending unknown wink ID's 

### ISSUE THREAD

**Issue by johanos** [VentanaIoT/Ventana#88]

**Comment by allydurks** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10134275-208277085_3-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by allydurks** [comment]
added catches in the case that no wink device is associated with a vumark id for status, change_power, change_brightness. Pushed onto branch "bugFixing"
